AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Rank-4 agent skeleton for whaddya-want

Globals:
  Function:
    Timeout: 30
    Runtime: python3.11
    MemorySize: 512

Resources:
  AgentStateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: gsi1pk
          AttributeType: S
        - AttributeName: gsi1sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: gsi1
          KeySchema:
            - AttributeName: gsi1pk
              KeyType: HASH
            - AttributeName: gsi1sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  SharedDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: whaddya-want-shared
      Description: Shared Python deps + agent_core
      ContentUri: layers/shared
      CompatibleRuntimes:
        - python3.11
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.11
      BuildProperties:
        # This tells SAM exactly how to build the layer:
        # - Install Python deps from requirements.txt into /asset-output/python
        # - Copy your existing python/ tree under layers/shared into the same directory.
        Commands:
          - pip install -r requirements.txt -t /asset-output/python

  BrokerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/broker/
      Handler: app.handler
      Environment:
        Variables:
          # Bedrock model used by AwsModelClient.from_env()
          MODEL_ID: meta.llama3-1-8b-instruct-v1:0
          # Unified state + memory table
          AGENT_STATE_TABLE: !Ref AgentStateTable
          # Logical agent ID (used as partition key prefix)
          AGENT_ID: marvin
          # Optional: default Polly voice for agent speech (fallback is Matthew)
          # AGENT_VOICE_ID: Matthew
          # Optional: S3 bucket for storing synthesized audio (if you wire one)
          # AUDIO_BUCKET: your-audio-bucket-name
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AgentStateTable
        - Version: '2012-10-17'
          Statement:
            # Bedrock for LLM calls
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
                - bedrock:Converse
                - bedrock:ConverseStream
              Resource: '*'
            # Polly for speech synthesis
            - Effect: Allow
              Action:
                - polly:SynthesizeSpeech
              Resource: '*'
            # If you later configure AUDIO_BUCKET, you can uncomment and tighten this:
            # - Effect: Allow
            #   Action:
            #     - s3:PutObject
            #   Resource:
            #     - arn:aws:s3:::your-audio-bucket-name/*
      Events:
        Api:
          Type: Api
          Properties:
            Path: /agent
            Method: POST
      Layers:
        - !Ref SharedDependenciesLayer

  AgentHeartbeatFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/agent_heartbeat/
      Handler: handler.handler
      Environment:
        Variables:
          # Must match the model you actually want the heartbeat to use
          MODEL_ID: meta.llama3-1-8b-instruct-v1:0
          AGENT_STATE_TABLE: !Ref AgentStateTable
          AGENT_ID: marvin
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AgentStateTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
                - bedrock:Converse
                - bedrock:ConverseStream
              Resource: '*'
      Layers:
        - !Ref SharedDependenciesLayer

  AgentHeartbeatRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: rate(5 minutes)
      State: ENABLED
      Targets:
        - Arn: !GetAtt AgentHeartbeatFunction.Arn
          Id: AgentHeartbeatTarget

  AgentHeartbeatPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AgentHeartbeatFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt AgentHeartbeatRule.Arn

Outputs:
  BrokerEndpoint:
    Description: Invoke URL for the conversation broker
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/agent"

  RestApiId:
    Description: API Gateway REST API ID
    Value: !Ref ServerlessRestApi

  AgentStateTableName:
    Description: DynamoDB table for agent unified state+memory
    Value: !Ref AgentStateTable

  BrokerFunctionArn:
    Description: Broker Lambda ARN
    Value: !GetAtt BrokerFunction.Arn

  AgentHeartbeatFunctionArn:
    Description: Heartbeat Lambda ARN
    Value: !GetAtt AgentHeartbeatFunction.Arn
