AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless resources for the AI companion conversation broker

Globals:
  Function:
    Runtime: python3.11
    Timeout: 30
    MemorySize: 512
    Architectures: [arm64]
    Environment:
      Variables:
        CONVERSATION_TABLE: !Ref ConversationTable
        AUDIO_BUCKET: !Ref AudioBucket
        LLM_SECRET_ID: !Ref LLMSecretArn
        POLLY_VOICE: Joanna
        HISTORY_LIMIT: 12

Parameters:
  LLMSecretArn:
    Type: String
    Description: ARN of the Secrets Manager secret containing the OpenAI/LLM API key

Resources:
  ConversationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sessionId
          AttributeType: S
        - AttributeName: sequence
          AttributeType: N
      KeySchema:
        - AttributeName: sessionId
          KeyType: HASH
        - AttributeName: sequence
          KeyType: RANGE

  AudioBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: shared-companion
      ContentUri: layers/shared
      CompatibleRuntimes:
        - python3.11
      RetentionPolicy: Delete

  BrokerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/broker/
      Handler: app.handler
      Layers:
        - !Ref SharedLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:Query
                - dynamodb:UpdateItem
              Resource: !GetAtt ConversationTable.Arn
            - Effect: Allow
              Action:
                - polly:SynthesizeSpeech
              Resource: '*'
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
              Resource: !Sub '${AudioBucket.Arn}/*'
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref LLMSecretArn
            - Effect: Allow
              Action:
                - rekognition:DetectLabels
                - rekognition:SearchFacesByImage
              Resource: '*'
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /ingest/audio
            Method: post

Outputs:
  BrokerEndpoint:
    Description: Invoke URL for the conversation broker
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/ingest/audio"
